name: mapbox_gl
description: A Flutter plugin for integrating Mapbox Maps inside a Flutter application on Android, iOS and web platfroms.
version: 0.14.0
homepage: https://github.com/mario-jerkovic/flutter_mapbox_gl

dependencies:
  flutter:
    sdk: flutter
  mapbox_gl_platform_interface:
    git:
      url: git@github.com:mario-jerkovic/flutter_mapbox_gl_platform_interface.git

#dependency_overrides:
#  mapbox_gl_platform_interface:
#    path: ./mapbox_gl_platform_interface

flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.mapboxgl
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  # Flutter versions prior to 1.10 did not support the flutter.plugin.platforms map.
  flutter: ">=2.0.0"
